### ISSUE TITLE
cm_vision .. No module named cmvision.msg while launching the file !!!

### ISSUE THREAD

**Issue by ziggBee30** [OSUrobotics/cmvision_3d#5]
ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
ERROR: cannot launch node of type [cmvision/cmvision]: cmvision
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/bin
ROS path [2]=/home/zubair/ros/
ROS path [3]=/home/zubair/catkin_ws/src
ROS path [4]=/home/zubair/ros_ws/src
ROS path [5]=/opt/ros/kinetic/share
process[color_controller-2]: started with pid [8375]
Traceback (most recent call last):
  File "/home/zubair/catkin_ws/src/cmvision_3d/scripts/color_controller.py", line 8, in <module>
    from cmvision.msg import Blobs
ImportError: No module named cmvision.msg
[color_controller-2] process has died [pid 8375, exit code 1, cmd /home/zubair/catkin_ws/src/cmvision_3d/scripts/color_controller.py depth_image:=camera/depth/image camera_topic:=/camera/color/camera_info __name:=color_controller __log:=/home/zubair/.ros/log/86bf0a02-0e1b-11e7-8d8c-5800e315aa80/color_controller-2.log].
log file: /home/zubair/.ros/log/86bf0a02-0e1b-11e7-8d8c-5800e315aa80/color_controller-2*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done

This is what i am getting when i launch the file color_tracker.launch ..

please help on how to fix this , i checked the messages folder there are no messages named cmvision.msgs .

thanks

**Comment by ziggBee30** [comment]
@ahubers

**Comment by ahubers** [comment]
@zubair123khan judging by your error, it looks like you don't have the `cmvision` package installed. Please keep in mind that `cmvision` and `cmvision_3d` are separate packages. I would recommend that you make sure to install all dependencies of `cmivision_3d`. I don't remember how to do that.

I can't help more than that because I haven't worked with ROS in 2-3 years.

**Comment by ahubers** [comment]
If installing [cmvision](http://wiki.ros.org/cmvision) does not help then please reopen this issue and hopefully the good folks at @OSUrobotics can assist.

**Comment by ziggBee30** [comment]
https://github.com/kbogert/cmvision/tree/indigo-devel 

is this is the pack i need to install in the source ,, 
this is what you talking about ???? 

@ahubers

**Comment by ahubers** [comment]
Yes it's this package http://wiki.ros.org/cmvision. Last time I checked it was hosted on Github via UT-Austin at https://github.com/utexas-bwi/cmvision. I can't help more than that, I haven't touch Ros since Hydro.
